apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: p6oyzlxqy-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/p6oyzlxqy-java-quarkus-gitops